owner: MarketingAXA
repo: monitoring-dz

sites:
  - name: AXA Algérie
    url: https://www.axa.dz
    method: GET
    expectedStatus: 200
    maxResponseTime: 5000

  - name: AXA DZ - e-Paiement Voyage
    url: https://voyage.axa.dz
    method: GET
    expectedStatus: 200
    maxResponseTime: 5000

status-website:
  baseUrl: /monitoring-dz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AXA Monitoring
  introTitle: "**AXA.dz Status Page**"
  introMessage: Ce site vous montre l’état de disponibilité du site AXA Algérie.
  navbar:
    - title: État
      href: /
    - title: GitHub
      href: https://github.com/MarketingAXA/monitoring-dz
